"""empty message

Revision ID: 206a56021cbb
Revises: 5db9890f5a80
Create Date: 2024-11-19 14:10:45.565564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206a56021cbb'
down_revision = '5db9890f5a80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videoId',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('videoId', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videoId')
    # ### end Alembic commands ###
