"""adding des table for the des of the about page for band

Revision ID: 3f329210bb5a
Revises: d58f1e2d57d0
Create Date: 2024-07-19 14:58:24.505936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f329210bb5a'
down_revision = 'd58f1e2d57d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('description')
    # ### end Alembic commands ###
