"""empty message

Revision ID: 82161c8c4d9d
Revises: 206a56021cbb
Create Date: 2024-11-19 14:31:38.963611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82161c8c4d9d'
down_revision = '206a56021cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videoid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('videoId', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('videoId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videoId',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"videoId_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('videoId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='videoId_pkey')
    )
    op.drop_table('videoid')
    # ### end Alembic commands ###
