"""adding products table

Revision ID: 86238b7f3906
Revises: 528f78f67cd0
Create Date: 2024-06-24 15:10:54.445155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86238b7f3906'
down_revision = '528f78f67cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('info', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
