"""adding ratings foreighn key colunm to the thingy

Revision ID: d58f1e2d57d0
Revises: 925ec608d6b7
Create Date: 2024-07-16 15:33:24.361582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd58f1e2d57d0'
down_revision = '925ec608d6b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_ratings_product_id_products'), 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ratings_product_id_products'), type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
